### PR TITLE
Add an option to detect top x hands, add FPS Counter

### PR DESCRIPTION
**Pull request by djthegr8**
This would help ppl who want to detect only one hand (eg. me)

### CODE REVIEW

**Comment by djthegr8** [comment]
Added an FPS Counter, for better benchmarking

**Comment by cansik** [comment]
@djthegr8 : The code you provided was not working with `-1`, if **zero** hands were present in the beginning. Otherwise it would not show all the hands but just as many as were detected in the first frame.

I decoupled `args.hands` now and created a new variable (a939fbedc0ba87b623fb5227d7d5631160461050). Please try to test your code with every eventualities. I will do it as well.

**Comment by djthegr8** [comment]
Sincere apologies, I had forgotten to test with `-1`, which I really shouldn't have.

**Comment by djthegr8** [comment]
yes, there should've been a different variable assigned saving `args.Hands` as it wouldn't continue to be `-1` after I've reassigned it. Extremely careless on my part, apologies again

**Pull request merged**
